#!/bin/bash

# Usage:
# ./gather [BASE_COLLECTION_PATH]
#
# where:
#   BASE_COLLECTION_PATH is an optional argument to define the path of the collection directory, defaults to
#   `/must-gather`

CMA_DEFAULT_NS="openshift-keda"
CMA_SUB_NAME="openshift-custom-metrics-autoscaler-operator"

# set working dir
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
# load helpers
source ${SCRIPT_DIR}/common

# read must-gather path
BASE_COLLECTION_PATH="${1:-/must-gather}"
# ensure path exists and enter it
mkdir -p "${BASE_COLLECTION_PATH}"
cd $BASE_COLLECTION_PATH

# define a local cache for kube API to improve the discovery and avoid client-side throttling
export KUBECACHEDIR=$(mktemp -d)

# find namespace
CMA_NS=$(oc get subs --cache-dir=${KUBECACHEDIR} -A \
  -o template \
  --template '{{range .items}}{{if eq .spec.name "'"${CMA_SUB_NAME}"'"}}{{.metadata.namespace}}{{end}}{{end}}')

# use namespace from subscription, otherwise use default
if [ -z "${CMA_NS}" ]; then
    echo "${CMA_SUB_NAME} subscription not detected. Using ${CMA_DEFAULT_NS} as default namespace"
    CMA_NS=${CMA_DEFAULT_NS}
fi

echo "Must-gather script started with KUBECACHEDIR: ${KUBECACHEDIR}"
echo "For must-gather version file check ${BASE_COLLECTION_PATH}/version"
echo "For script debug logs check ${BASE_COLLECTION_PATH}/gather-debug.log"

# generate /must-gather/version file with product and version
# see https://github.com/openshift/enhancements/blob/master/enhancements/oc/must-gather.md#must-gather-images
echo "${CMA_SUB_NAME}" > ${BASE_COLLECTION_PATH}/version
echo $(oc get packagemanifests ${CMA_SUB_NAME} --cache-dir=${KUBECACHEDIR} \
  -n openshift-marketplace \
  -o jsonpath='{.status.channels[?(@.name=="stable")].currentCSVDesc.version}') >> ${BASE_COLLECTION_PATH}/version

# init list of custom resources
cluster_resources+=(
  kedacontroller
  scaledjob
  scaledobject
  triggerauthentication
  clustertriggerauthentication
)
# add operator namespace
cluster_resources+=(ns/$CMA_NS)

# run the collection of resources
log "Collecting resources for custom-metrics-autoscaler" >> "${BASE_COLLECTION_PATH}/gather-debug.log"
for resource in ${cluster_resources[@]}; do
  log "Inspecting $resource" >> "${BASE_COLLECTION_PATH}/gather-debug.log"
  oc adm inspect --cache-dir=${KUBECACHEDIR} --dest-dir ${BASE_COLLECTION_PATH} ${resource} >> "${BASE_COLLECTION_PATH}/gather-debug.log" 2>&1
  log "Finish inspecting $resource" >> "${BASE_COLLECTION_PATH}/gather-debug.log"
done

log "Collection completed for custom-metrics-autoscaler" >> "${BASE_COLLECTION_PATH}/gather-debug.log"

# success
exit 0
